# Generated by Django 4.0.10 on 2023-08-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRErsetzunge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wort', models.CharField(max_length=30)),
                ('ersetzung', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PronomenErsetzungMaennlich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wort', models.CharField(max_length=15)),
                ('ersetzung', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PronomenErsetzungWeiblich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wort', models.CharField(max_length=15)),
                ('ersetzung', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VerbenErsetzungGegenwart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wort', models.CharField(max_length=20)),
                ('ersetzung', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VerbenErsetzungSatzendeGegenwart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wort', models.CharField(max_length=20)),
                ('ersetzung', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VerbenErsetzungVergangenheitsform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wort', models.CharField(max_length=20)),
                ('hilfsverb', models.CharField(max_length=10)),
                ('ersetzung', models.CharField(max_length=30)),
            ],
        ),
    ]
