pronomen_ersetzungen_m = {
    # Drittpersonen müssen zuerst ersetzt werden, sonst wird die Ersetzung von der
    # Erst- auf die Drittperson erneut übersetzt
    "er": ["dieser", "A"],
    "sie": ["diese", "A"],
    "ihn": ["diesen", "A"],
    "ihr": ["dieser", "A"],
    "ihm": ["diesem", "A"],
    # Männliche Pronomenersetzung
    "ich": ["er", "B"],
    "mein": ["sein", "B"],
    "meine": ["seine", "B"],
    "meinen": ["seinen", "B"],
    "meinem": ["seinem", "B"],
    "meiner": ["seiner", "B"],
    "meinerseits": ["seinerseits", "B"],
    "meines": ["seines", "B"],
    "mich": ["ihn/sich", ""],
    "mir": ["ihm", "B"],
    "wir": ["sie", "B"],
    "unser": ["ihr", "B"],
    "unsere": ["ihre", "B"],
    "unserem": ["ihrem", "B"],
    "uns": ["sich/ihnen", "B"],
}

pronomen_ersetzungen_w = {
    # Drittpersonen müssen zuerst ersetzt werden, sonst wird die Ersetzung von der
    # Erst- auf die Dritttperson erneut übersetzt
    "er": ["dieser", "A"],
    "sie": ["diese", "A"],
    "ihn": ["diesen", "A"],
    "ihr": ["dieser", "A"],
    "ihm": ["diesem", "A"],
    # Weibliche Pronomenersetzung
    "ich": ["sie", "B"],
    "mein": ["ihr", "B"],
    "meine": ["ihre", "B"],
    "meinen": ["ihren", "B"],
    "meinem": ["ihrem", "B"],
    "meiner": ["ihrer", "B"],
    "meinerseits": ["ihrerseits", "B"],
    "meines": ["ihres", "B"],
    "mich": ["sie/sich", "B"],
    "mir": ["ihr", "B"],
    "wir": ["sie", "B"],
    "unser": ["ihr", "B"],
    "unsere": ["ihre", "B"],
    "unserem": ["ihrem", "B"],
    "uns": ["sich/ihnen", "B"],
}

ocr_ersetzungen = {
    "lch": "Ich",
    "ln": "In",
    "lnformation": "Information",
    "lnformationen": "Informationen",
    "lnfo": "Info",
    "lnfos": "Infos",
    "ldee": "Idee",
    "ldeen": "Ideen",
    "lnsider": "Insider",
    "lrrtum": "Irrtum",
    "ldentifikation": "Identifikation",
    "lnstruktionen": "Instruktionen",
    "lnteresse": "Interesse",
    "lrgendwann": "Irgendwann",
    "lnhalt": "Inhalt",
    "lnhaltlich": "Inhaltlich",
    "lnterpretation": "Interpretation",
    "lnitiative": "Initiative",
    "lhnen": "Ihnen",
    "enruähnt": "erwähnt",
    "enruähnen": "erwähnen",
    "enryähnen": "erwähnen",
    "enrvähnen": "erwähnen",
    "enruartet": "erwartet",
    "normalenrueise": "normalerweise",
    "lnhaber": "Inhaber",
    "venruenden": "verwenden",
    "lmmobilien": "Immobilien",
    "lnvestition": "Investition",
    "lnvestitionen": "Investitionen",
    "lrgendwo": "Irgendwo",
    "lrgendwie": "Irgendwie",
    "lnternet": "Internet",
    "lnternetseite": "Internetseite",
    "lndien": "Indien",
    "ltalien": "Italien",
    "lnvestor": "Investor",
    "lnvestoren": "Investoren",
    "lnhaberaktien": "Inhaberaktien",
    "lgor": "Igor",
    "lnteressent": "Interessent",
    "lnteressenten": "Interessenten",
    "lnhalte": "Inhalte",
    "lndustrie": "Industrie",
    "lnvestment": "Investment",
    "lnvestments": "Investments",
    "lhre": "Ihre",
    "lhr": "Ihr",
    "lhrem": "Ihrem",
    "lhres": "Ihres",
}

verben_ersetzung_praesens = {
    "hat": "habe",
    "ist": "sei",
    "soll": "solle",
    "kann": "könne",
    "hatte": "habe",
    "weiss": "wisse",
    "darf": "dürfe",
    "heisst": "heisse",
    "trifft": "treffe",
    "glaubt": "glaube",
    "schenkt": "schenke",
    "braucht": "brauche",
    "kauft": "kaufe",
    "will": "wolle",
    "kennt": "kenne",
    "lebt": "lebe",
    "übergibt": "übergebe",
    "tauscht": "tausche",
    "spielt": "spiele",
    "fühlt": "fühle",
    "hilft": "helfe",
    "schaut": "schaue",
    "denkt": "denke",
    "bringt": "bringe",
    "bemerkt": "bemerke",
    "benötigt": "benötige",
    "verfügt": "verfüge",
    "verdient": "verdiene",
    "möchte": "wolle",
    "sagt": "sage",
    "wohnt": "wohne",
    "besitzt": "besitze",
    "fällt": "falle",
    "verlange": "verlangte",
    "lauft": "laufe",
    "durchsucht": "durchsuche",
    "arbeitet": "arbeite",
    "nimmt": "nehme",
    "vermutet": "vermute",
    "stamme": "stammte",
    "belastet": "belaste",
    "holt": "hole",
    "täuscht": "täusche",
    "verliert": "verliere",
    "zielt": "ziele",
    "erhält": "erhalte",
    "interessiert": "interessiere",
    "steigt": "steige",
    "schaue": "schaue",
    "übernimmt": "übernehme",
    "bewertet": "bewerte",
    "betrachtet": "betrachte",
    "tätigt": "tätige",
    "wirft": "werfe",
    "reagiert": "reagiere",
    "erzielt": "erziele",
    "zahlt": "zahle",
    "generiert": "generiere",
    "öffnet": "öffne",
    "sucht": "suche",
    "trägt": "trage",
    "lenkt": "lenke",
    "führt": "führe",
    "erbringt": "erbringe",
    "hält": "halte",
    "vertreibt": "vertreibe",
    "vermag": "vermöge",
    "übt": "übe",

    # neuer Absatz in VBA
    "bin": "sei",
    "haben": "hätten",
    "sind": "seien",
    "machen": "machten",
    "benötigen": "benötigten",
    "hatten": "hätten",
    "stammen": "stammten",
    "vertreiben": "vertrieben",
    "entwickelt": "entwickle",
    "sitzt": "sitze",

    # neuer Absatz in VBA
    "muss": "müsse",
    "wird": "werde",
    "gilt": "gelte",
    "geht": "gehe",
    "gibt": "gebe",
    "steht": "stehe",
    "befindet": "befinde",
    "kommt": "komme",
    "müssen": "müssten",
    "können": "könnten",
    "dürfen": "dürften",
    "stellt": "stelle",
    "zeigt": "zeige",
    "erstreckt": "erstrecke",
    "aussieht": "aussehe",
    "ergibt": "ergebe",
    "macht": "mache",
    "liegt": "liege",
    "hängt": "hänge",
    "bleibt": "bleibe",
    "stimmt": "stimme",
    "lautet": "laute",
    "bezieht": "beziehe",
    "stattfindet": "stattfinde",
    "findet": "finde",
    "entspricht": "entspreche",
    "entsprechen": "entsprächen",
    "handelt": "handle",
    "fehlt": "fehle",
    "fehlen": "fehlten",
    "tut": "tue",
    "besteht": "bestehe",
    "setzt": "setze",
    "angeht": "angehe",
    "sieht": "sehe",
    "funktioniert": "funktioniere",
    "anbelangt": "anbelange",
    "dient": "diene",
    "erwartet": "erwarte",
    "enthält": "enthalte",
    "betrifft": "betreffe",
    "stimmen": "stimmten",
    "läuft": "laufe",
    "stammt": "stamme",
    "kostet": "koste",
    "passt": "passe",
    "entsteht": "entstehe",
    "könnte": "könne",
    "folgt": "folge",
    "datiert": "datiere",
    "gehört": "gehöre",
    "gelingt": "gelinge",
    "vorsieht": "vorsehe",
    "spricht": "spreche",
    "beträgt": "betrage",
    "geschieht": "geschehe",
    "fängt": "fange",
    "fliesst": "fliesse",
    "fragt": "frage",
    "scheint": "scheine",
}

# Dies braucht es in der Python Version gar nicht
satzende_praetaeritum = {
    "war": "gewesen sei",
    "waren": "gewesen seien",
    "kam": "gekommen sei",
    "kamen": "gekommen seien",
    "blieb": "geblieben sei",
    "blieben": "geblieben seien",
    "gab": "gegeben habe",
    "ging": "gegangen sei",
    "wurde": "worden sei",
    "befand": "befunden habe",
    "machte": "gemacht habe",
    "wusste": "gewusst habe",
    "sagte": "gesagt habe",
    "sagten": "gesagt hätten",
    "brauchte": "gebraucht habe",
    "brauchten": "gebraucht hätten",
    "hielt": "gehalten habe",
    "hielten": "gehalten hätten",
    "wollte": "habe gewollt",
    "wollten": "hätten gewollt",
    "dachte": "habe gedacht",
    "dachten": "hätten gedacht",
    "lautete": "habe gelautet",
    "lauteten": "hätten gelautet",
    "stand": "habe gestanden",
    "standen": "hätten gestanden",
    "verlangte": "habe verlangt",
    "verlangten": "hätten verlangt",
}

verben_ersetzung_praeteritum = {
    "war": ["sei", "gewesen"],
    "waren": ["seien", "gewesen"],
    "hatte": ["habe", "gehabt"],
    "hatten": ["hätten", "gehabt"],
    "musste": ["habe", "müssen"],
    "mussten": ["hätten", "müssen"],
    "fuhr": ["sei", "gefahren"],
    "fuhren": ["seien", "gefahren"],
    "trug": ["habe", "getragen"],
    "trugen": ["hätten", "getragen"],
    "befand": ["habe", "befunden"],
    "befanden": ["hätten", "befunden"],
    "lief": ["sei", "gelaufen"],
    "liefen": ["seien", "gelaufen"],
    "stellte": ["habe", "gestellt"],
    "stellten": ["hätten", "gestellt"],
    "fragte": ["habe", "gefragt"],
    "fragten": ["hätten", "getragen"],
    "ging": ["sei", "gegangen"],
    "gingen": ["seien", "gegangen"],
    "blieb": ["sei", "geblieben"],
    "blieben": ["sei", "geblieben"],
    "kannte": ["habe", "gekannt"],
    "kannten": ["hätten", "gekannt"],
    "wusste": ["habe", "gewusst"],
    "wussten": ["hätten", "gewusst"],
    "stand": ["habe", "gestanden"],
    "standen": ["hätten", "gestanden"],
    "dachte": ["habe", "gedacht"],
    "dachten": ["hätten", "gedacht"],
    "nahm": ["habe", "genommen"],
    "nahmen": ["hätten", "genommen"],
    "sah": ["habe", "gesehen"],
    "sahen": ["hätten", "gesehen"],
    "kam": ["sei", "gekommen"],
    "kamen": ["seien", "gekommen"],
    "sagte": ["habe", "gesagt"],
    "sagten": ["hätten", "gesagt"],
    "wurde": ["sei", "worden"],
    "wurden": ["seien", "worden"],
    "brauchte": ["habe", "gebraucht"],
    "brauchten": ["hätten", "gebraucht"],
    "benötigte": ["habe", "benötigt"],
    "benötigten": ["hätten", "benötigt"],
    "konnte": ["habe", "gekonnt"],
    "konnten": ["hätten", "gekonnt"],
    "gab": ["habe", "gegeben"],
    "durfte": ["habe", "gedurft"],
    "durften": ["hätten", "dürfen"],
    "machte": ["habe", "gemacht"],
    "machten": ["hätten", "gemacht"],
    "spielte": ["habe", "gespielt"],
    "spielten": ["hätten", "gespielt"],
    "hielt": ["habe", "gehalten"],
    "hielten": ["hätten", "gehalten"],
    "wollte": ["habe", "wollen"],
    "wollten": ["hätten", "wollen"],
    "diente": ["habe", "gedient"],
    "dienten": ["hätten", "gedient"],
    "versuchte": ["habe", "versucht"],
    "versuchten": ["hätten", "versucht"],
    "brachte": ["habe", "gebracht"],
    "brachten": ["hätten", "gebracht"],
    "fand": ["habe", "gefunden"],
    "fanden": ["hätten", "gefunden"],
    "geriet": ["sei", "geraten"],
    "gerieten": ["seien", "geraten"],
    "fuhren": ["seien", "gefahren"],
    "verbrachte": ["habe", "verbracht"],
    "verbrachten": ["hätten", "verbracht"],
    "trank": ["habe", "getrunken"],
    "tranken": ["hätten", "getrunken"],
    "unterhielt": ["habe", "unterhalten"],
    "unterhielten": ["hätten", "unterhalten"],
    "besass": ["habe", "besessen"],
    "besassen": ["hätten", "besessen"],
    "fiel": ["sei", "gefallen"],
    "fielen": ["seien", "gefallen"],
    "verlangte": ["habe", "verlangt"],
    "verlangten": ["hätten", "verlangt"],
    "passierte": ["sei", "passiert"],
    "erklärte": ["habe", "erklärt"],
    "erklärten": ["hätten", "erklärt"],
    "traf": ["habe", "getroffen"],
    "trafen": ["hätten", "getroffen"],
    "bekam": ["habe", "bekommen"],
    "bekamen": ["hätten", "bekommen"],
    "löschte": ["habe", "gelöscht"],
    "löschten": ["hätten", "gelöscht"],
    "kostete": ["habe", "gekostet"],
    "vermutete": ["habe", "vermutet"],
    "vermuteten": ["hätten", "vermutet"],
    "passte": ["habe", "gepasst"],
    "passten": ["hätten", "gepasst"],
    "holte": ["habe", "geholt"],
    "holten": ["hätten", "geholt"],
    "zeigte": ["habe", "gezeigt"],
    "zeigten": ["hätten", "gezeigt"],
    "telefonierte": ["habe", "telefoniert"],
    "telefonierten": ["hätten", "telefoniert"],
    "bat": ["habe", "gebeten"],
    "baten": ["hätten", "gebeten"],
    "hörte": ["habe", "gehört"],
    "hörten": ["hätten", "gehört"],
    "sass": ["habe", "gesessen"],
    "sassen": ["hätten", "gesessen"],
    "schilderte": ["habe", "geschildert"],
    "schilderten": ["hätten", "geschildert"],
    "schrieb": ["habe", "geschrieben"],
    "schrieben": ["hätten", "geschrieben"],
    "logierte": ["habe", "logiert"],
    "logierten": ["hätten", "logiert"],
    "funktionierte": ["habe", "funktioniert"],
    "funktionierten": ["hätten", "funktioniert"],
    "lag": ["sei", "gelegen"],
    "lagen": ["seien", "gelegen"],
    "täuschte": ["habe", "getäuscht"],
    "täuschten": ["hätten", "getäuscht"],
    "zielte": ["habe", "gezielt"],
    "zielten": ["hätten", "gezielt"],
    "antwortete": ["habe", "geantwortet"],
    "antworteten": ["hätten", "geantwortet"],
    "rief": ["habe", "gerufen"],
    "riefen": ["hätten", "gerufen"],
    "stieg": ["sei", "gestiegen"],
    "stiegen": ["seien", "gestiegen"],
    "schaute": ["habe", "geschaut"],
    "schauten": ["hätten", "geschaut"],
    "übernahm": ["habe", "übernommen"],
    "übernahmen": ["hätten", "übernommen"],
    "öffnete": ["habe", "geöffnet"],
    "öffneten": ["hätten", "geöffnet"],
    "reagierte": ["habe", "reagiert"],
    "reagierten": ["hätten", "reagiert"],
    "begab": ["habe", "begeben"],
    "begaben": ["hätten", "begeben"],
    "führte": ["habe", "geführt"],
    "führten": ["hätten", "geführt"],
    "sprach": ["habe", "gesprochen"],
    "sprachen": ["hätten", "gesprochen"],
    "stiess": ["habe", "gestossen"],
    "stiessen": ["hätten", "gestossen"],
    "gelangte": ["sei", "gelangt"],
    "gelangten": ["seien", "gelangt"],
    "schloss": ["habe", "geschlossen"],
    "schlossen": ["hätten", "geschlossen"],
    "folgte": ["sei", "gefolgt"],
    "folgten": ["seien", "gefolgt"],
    "meinte": ["habe", "gemeint"],
    "meinten": ["hätten", "gemeint"],
    "zahlte": ["habe", "gezahlt"],
    "zahlten": ["hätten", "gezahlt"],
    "erfolgte": ["sei", "erfolgt"],
    "erfolgten": ["seien", "erfolgt"],
    "lautete": ["habe", "gelautet"],
    "lauteten": ["hätten", "gelautet"],
    "beantragte": ["habe", "beantragt"],
    "beantragten": ["hätten", "beantragt"],
    "suchte": ["habe", "gesucht"],
    "suchten": ["hätten", "gesucht"],
    "warf": ["habe", "geworfen"],
    "warfen": ["hätten", "geworfen"],
    "schuldete": ["habe", "geschuldet"],
    "schuldeten": ["hätten", "geschuldet"],
    "erhielt": ["habe", "erhalten"],
    "erhielten": ["hätten", "erhalten"],
    "liess": ["habe", "gelassen"],
    "liessen": ["hätten", "gelassen"],
    "hiess": ["habe", "geheissen"],
    "hiessen": ["hätten", "geheissen"],
    "tat": ["habe", "getan"],
    "taten": ["hätten", "getan"],
    "glaubte": ["habe", "geglaubt"],
    "glaubten": ["hätten", "geglaubt"],
    "half": ["habe", "geholfen"],
    "halfen": ["hätten", "geholfen"],
    "ass": ["habe", "gegessen"],
    "assen": ["hätten", "gegessen"],
    "las": ["habe", "gelesen"],
    "lasen": ["hätten", "gelesen"],
    "zog": ["habe", "gezogen"],
    "zogen": ["hätten", "gezogen"],
    "schlief": ["habe", "geschlafen"],
    "schliefen": ["hätten", "geschlafen"],
    "begann": ["habe", "begonnen"],
    "begannen": ["hätten", "begonnen"],
    "legte": ["habe", "gelegt"],
    "legten": ["hätten", "gelegt"],
    "wehrte": ["habe", "gewehrt"],
    "wehrten": ["hätten", "gewehrt"],
    "spuckte": ["habe", "gespuckt"],
    "spuckten": ["hätten", "gespuckt"],
    "explodierte": ["sei", "explodiert"],
    "explodierten": ["seien", "explodiert"],
    "schleuderte": ["habe", "geschleudert"],
    "schleuderten": ["hätten", "geschleudert"],
    "schubste": ["habe", "geschubst"],
    "schubsten": ["hätten", "geschubst"],
    "drückte": ["habe", "gedrückt"],
    "drückten": ["hätten", "gedrückt"],
    "beobachtete": ["habe", "beobachtet"],
    "beobachteten": ["hätten", "beobachtet"],
    "winselte": ["habe", "gewinselt"],
    "winselten": ["hätten", "gewinselt"],
    "bellte": ["habe", "gebellt"],
    "bellten": ["hätten", "gebellt"],
    "stöhnte": ["habe", "gestöhnt"],
    "stöhnten": ["hätten", "gestöhnt"],
    "leckte": ["habe", "geleckt"],
    "leckten": ["hätten", "geleckt"],
    "bewegte": ["habe", "bewegt"],
    "bewegten": ["hätten", "bewegt"],
    "näherte": ["habe", "genähert"],
    "näherten": ["hätten", "genähert"],
    "verhielt": ["habe", "verhalten"],
    "verhielten": ["hätten", "verhalten"],
    "behandelte": ["habe", "behandelt"],
    "behandelten": ["hätten", "behandelt"],
    "hob": ["habe", "gehoben"],
    "hoben": ["hätten", "gehoben"],
    "flog": ["sei", "geflogen"],
    "flogen": ["seien", "geflogen"],
    "landete": ["sei", "gelandet"],
    "landeten": ["seien", "gelandet"],
    "wickelte": ["habe", "gewickelt"],
    "wickelten": ["hätten", "gewickelt"],
    "vernahm": ["habe", "vernommen"],
    "vernahmen": ["hätten", "vernommen"],
    "entschied": ["habe", "entschieden"],
    "entschieden": ["hätten", "entschieden"],
    "weigerte": ["habe", "geweigert"],
    "weigerten": ["hätten", "geweigert"],
    "insistierte": ["habe", "insistiert"],
    "insistierten": ["hätten", "insistiert"],
    "kaufte": ["habe", "gekauft"],
    "kauften": ["hätten", "gekauft"],
    "arbeitete": ["habe", "gearbeitet"],
    "arbeiteten": ["hätten", "gearbeitet"],
    "fühlte": ["habe", "gefühlt"],
    "fühlten": ["hätten", "gefühlt"],
    "lebte": ["habe", "gelebt"],
    "lebten": ["hätten", "gelebt"],
    "starb": ["sei", "gestorben"],
    "starben": ["seien", "gestorben"],
    "studierte": ["habe", "studiert"],
    "studierten": ["hätten", "studiert"],
    "reiste": ["sei", "gereist"],
    "reisten": ["seien", "gereist"],
    "träumte": ["habe", "geträumt"],
    "träumten": ["hätten", "geträumt"],
    "verkaufte": ["habe", "verkauft"],
    "verkauften": ["hätten", "verkauft"],
    "lernte": ["habe", "gelernt"],
    "lernten": ["hätten", "gelernt"],
    "weinte": ["habe", "geweint"],
    "weinten": ["hätten", "geweint"],
    "sang": ["habe", "gesungen"],
    "sangen": ["hätten", "gesungen"],
    "tanzte": ["habe", "getanzt"],
    "tanzten": ["hätten", "getanzt"],
    "malte": ["habe", "gemalt"],
    "malten": ["hätten", "gemalt"],
    "setzte": ["habe", "gesetzt"],
    "setzten": ["hätten", "gesetzt"],
    "meldete": ["habe", "gemeldet"],
    "meldeten": ["hätten", "gemeldet"],
    "schaffte": ["habe", "geschafft"],
    "schafften": ["hätten", "geschafft"],
    "bezahlte": ["habe", "bezahlt"],
    "bezahlten": ["hätten", "bezahlt"],
    "meldete": ["habe", "gemeldet"],
    "meldeten": ["hätten", "gemeldet"],
    "geschah": ["sei", "geschehen"],
    "kontaktierte": ["habe", "kontaktiert"],
    "kontaktierten": ["hätten", "kontaktiert"],
    "kontrollierte": ["habe", "kontrolliert"],
    "kontrollierten": ["hätten", "kontrolliert"],
    "schenkte": ["habe", "geschenkt"],
    "schenkten": ["hätten", "geschenkt"],
    "leistete": ["habe", "geleistet"],
    "leisteten": ["hätten", "geleistet"],
    "beorderte": ["habe", "beordert"],
    "beorderten": ["hätten", "beordert"],
    "erzählte": ["habe", "erzählt"],
    "erzählten": ["hätten", "erzählt"],
    "organisierte": ["habe", "organisiert"],
    "organisierten": ["hätten", "organisiert"],
    "präsentierte": ["habe", "präsentiert"],
    "präsentierten": ["hätten", "präsentiert"],
    "produzierte": ["habe", "produziert"],
    "produzierten": ["hätten", "produziert"],
    "fehlte": ["habe", "gefehlt"],
    "fehlten": ["hätten", "gefehlt"],
    "teilte": ["habe", "geteilt"],
    "teilten": ["hätten", "geteilt"],
    "betreute": ["habe", "betreut"],
    "betreuten": ["hätten", "betreut"],
    "strich": ["habe", "gestrichen"],
    "strichen": ["hätten", "gestrichen"],
    "verlegte": ["habe", "verlegt"],
    "verlegten": ["hätten", "verlegt"],
    "bestand": ["habe", "bestanden"],
    "bestanden": ["hätten", "bestanden"],
    "eröffnete": ["habe", "eröffnet"],
    "eröffneten": ["hätten", "eröffnet"],
    "sendete": ["habe", "gesendet"],
    "sendeten": ["hätten", "gesendet"],
    "rechnete": ["habe", "gerechnet"],
    "rechneten": ["hätten", "gerechnet"],
    "stützte": ["habe", "gestützt"],
    "stützten": ["hätten", "gestützt"],
    "generierte": ["habe", "generiert"],
    "generierten": ["hätten", "generiert"],
    "handelte": ["habe", "gehandelt"],
    "handelten": ["hätten", "gehandelt"],
    "schaltete": ["habe", "geschaltet"],
    "schalteten": ["hätten", "geschaltet"],
    "fügte": ["habe", "gefügt"],
    "fügten": ["hätten", "gefügt"],
    "profitierte": ["habe", "profitiert"],
    "profitierten": ["hätten", "profitiert"],
    "sicherte": ["habe", "gesichert"],
    "sicherten": ["hätten", "gesichert"],
    "verliess": ["habe", "verlassen"],
    "verliessen": ["hätten", "verlassen"],
    "fing": ["habe", "gefangen"],
    "fingen": ["hätten", "gefangen"],
    "entstand": ["sei", "entstanden"],
    "entstanden": ["seien", "entstanden"],
    "unterschrieb": ["habe", "unterschrieben"],
    "unterschrieben": ["hätten", "unterschrieben"],
    "belief": ["habe", "belaufen"],
    "beliefen": ["hätten", "belaufen"],
    "verfügte": ["habe", "verfügt"],
    "verfügten": ["hätten", "verfügt"],
    "erwähnte": ["habe", "erwähnt"],
    "erwähnten": ["hätten", "erwähnt"],
    "finanzierte": ["habe", "finanziert"],
    "finanzierten": ["hätten", "finanziert"],
    "herrschte": ["habe", "geherrscht"],
    "herrschten": ["hätten", "geherrscht"],
    "klingelte": ["habe", "geklingelt"],
    "klingelten": ["hätten", "geklingelt"],
    "schickte": ["habe", "geschickt"],
    "schickten": ["hätten", "geschickt"],
    "riet": ["habe", "geraten"],
    "rieten": ["hätten", "geraten"],
    "verstand": ["habe", "verstanden"],
    "gewährt": ["habe", "gewährt"],
    "gewährten": ["hätten", "gewährt"],
    "realisierte": ["habe", "realisiert"],
    "realisierten": ["hätten", "realisiert"],
    "veranstaltete": ["habe", "veranstaltet"],
    "veranstalteten": ["hätten", "veranstaltet"],
    "wählte": ["habe", "gewählt"],
    "wählten": ["hätten", "gewählt"],
    "löste": ["habe", "gelöst"],
    "lösten": ["hätten", "gelöst"],
    "trat": ["habe", "getreten"],
    "traten": ["hätten", "getreten"],
    "monierte": ["habe", "moniert"],
    "monierten": ["hätten", "moniert"],
    "merkte": ["habe", "gemerkt"],
    "merkten": ["hätten", "gemerkt"],
    "fruchtete": ["habe", "gefruchtet"],
    "fruchteten": ["hätten", "gefruchtet"],
    "verniedlichte": ["habe", "verniedlicht"],
    "verniedlichten": ["hätten", "verniedlicht"],
    "beschönigte": ["habe", "beschönigt"],
    "beschönigten": ["hätten", "beschönigt"],
    "rastete": ["sei", "gerastet"],
    "rasteten": ["seien", "gerastet"],
    "befürchtete": ["habe", "befürchtet"],
    "befürchteten": ["hätten", "befürchtet"],
    "wünschte": ["habe", "gewünscht"],
    "wünschten": ["hätten", "gewünscht"],
    "betrieb": ["habe", "betrieben"],
    "betrieben": ["hätten", "betrieben"],
    "vereinbarte": ["habe", "vereinbart"],
    "vereinbarten": ["hätten", "vereinbart"],
    "gingen": ["seien", "gegangen"],
    "unterzeichnete": ["habe", "unterzeichnet"],
    "informierte": ["habe", "informiert"],
    "informierten": ["hätten", "informiert"],
    "streckte": ["habe", "gestreckt"],
    "streckten": ["hätten", "gestreckt"],
    "druckte": ["habe", "gedruckt"],
    "druckten": ["hätten", "gedruckt"],
    "verneinte": ["habe", "verneint"],
    "verneinten": ["hätten", "verneint"],
    "bejahte": ["habe", "bejaht"],
    "bejahten": ["hätten", "bejaht"],
    "leitete": ["habe", "geleitet"],
    "leiteten": ["hätten", "geleitet"],
    "beauftragte": ["habe", "beauftragt"],
    "beauftragten": ["hätten", "beauftragt"],
    "speicherte": ["habe", "gespeichert"],
    "speicherten": ["hätten", "gespeichert"],
    "überliess": ["habe", "überlassen"],
    "überliessen": ["hätten", "überlassen"],
    "kehrte": ["sei", "gekehrt"],
    "kehrten": ["seien", "gekehrt"],
    "beruhigte": ["habe", "beruhigt"],
    "beruhigten": ["hätten", "beruhigt"],
    "erwartete": ["habe", "erwartet"],
    "erwarteten": ["hätten", "erwartet"],
    "kümmerte": ["habe", "gekümmert"],
    "kümmerten": ["hätten", "gekümmert"],
    "drohte": ["habe", "gedroht"],
    "drohten": ["hätten", "gedroht"],
    "bezog": ["habe", "bezogen"],
    "bezogen": ["hätten", "bezogen"],
    "erachtete": ["habe", "erachtet"],
    "erachteten": ["hätten", "erachtet"],
    "unterschieb": ["habe", "unterschrieben"],
    "berichtete": ["habe", "berichtet"],
    "berichteten": ["hätten", "berichtet"],
    "nannte": ["habe", "genannt"],
    "nannten": ["hätten", "genannt"],
    "beschloss": ["habe", "beschlossen"],
    "beschlossen": ["hätten", "beschlossen"],
    "besprach": ["habe", "besprochen"],
    "besprachen": ["hätten", "besprochen"],
    "dauerte": ["habe", "gedauert"],
    "dauerten": ["hätten", "gedauert"],
    "richtete": ["habe", "gerichtet"],
    "richteten": ["hätten", "gerichtet"],
    "erstellte": ["habe", "erstellt"],
    "erstellten": ["hätten", "erstellt"],
    "entnahm": ["habe", "entnommen"],
    "entnahmen": ["hätten", "entnommen"],
    "bestimmte": ["habe", "bestimmt"],
    "bestimmten": ["hätten", "bestimmt"],
    "entschloss": ["habe", "entschlossen"],
    "entschlossen": ["hätten", "entschlossen"],
    "schwärmte": ["habe", "geschwärmt"],
    "schwärmten": ["hätten", "geschwärmt"],
    "beteiligte": ["habe", "beteiligt"],
    "wies": ["habe", "gewiesen"],
    "wiesen": ["hätten", "gewiesen"],
    "forderte": ["habe", "gefordert"],
    "forderten": ["hätten", "gefordert"],
    "sandte": ["habe", "gesendet"],
    "sandten": ["hätten", "gesendet"],
    "hoffte": ["habe", "gehofft"],
    "hofften": ["hätten", "gehofft"],
    "forschte": ["habe", "geforscht"],
    "forschten": ["hätten", "geforscht"],
    "investierte": ["habe", "investiert"],
    "investierten": ["hätten", "investiert"],
    "entsprach": ["habe", "entsprochen"],
    "entsprachen": ["hätten", "entsprochen"],
    "versicherte": ["habe", "versichert"],
    "versicherten": ["hätten", "versichert"],
    "vermarktete": ["habe", "vermarktet"],
    "vermarkteten": ["hätten", "vermarktet"],
    "leaste": ["habe", "geleast"],
    "leasten": ["hätten", "geleast"],
    "begründete": ["habe", "begründet"],
    "existierte": ["habe", "existiert"],
    "existierten": ["hätten", "existiert"],
    "leaste": ["habe", "geleast"],
    "veröffentlichte": ["habe", "veröffentlicht"],
    "überwies": ["habe", "überwiesen"],
    "überwiesen": ["hätten", "überwiesen"],
    "verwendete": ["habe", "verwendet"],
    "entgegnete": ["habe", "entgegnet"],
    "entgegneten": ["hätten", "entgegnet"],
    "floss": ["sei", "geflossen"],
    "flossen": ["seien", "geflossen"],
    "besuchte": ["habe", "besucht"],
    "stoppte": ["habe", "gestoppt"],
    "stoppten": ["hätten", "gestoppt"],
    "kritisierte": ["habe", "kritisiert"],
    "kritisierten": ["hätten", "kritisiert"],
    "empfand": ["habe", "empfunden"],
    "empfanden": ["hätten", "empfunden"],
    "sollte": ["habe", "sollen"],
    "sollten": ["hätten", "sollen"],
    "erbrachte": ["habe", "erbracht"],
    "erbrachten": ["hätten", "erbracht"],
    "kommunizierte": ["habe", "kommuniziert"],
    "einigte": ["habe", "geeinigt"],
    "einigten": ["hätten", "geeinigt"],
}

verben_zusammenfuegung = {
    "zurück gehalten": "zurückgehalten",
    "an gerufen": "angerufen",
    "ab geraten": "abgeraten",
    "zu gemacht": "zugemacht",
    "vor gesehen": "vorgesehen",
    "ab gestützt": "abgestützt",
    "heraus gekommen": "herausgekommen",
    "aus gewählt": "ausgewählt",
    "heraus gerückt": "herausgerückt",
    "rein komme": "reinkomme",
    "aus gegangen": "ausgegangen",
    "entgegen genommen": "entgegengenommen",
    "heraus gestellt": "herausgestellt",
    "aus gelöst": "ausgelöst",
    "ab getreten": "abgetreten",
    "aus gesehen": "ausgesehen",
    "vor gestellt": "vorgestellt",
    "zu gegangen": "zugegangen",
    "statt gefunden": "stattgefunden",
    "aus gerastet": "ausgerastet",
    "ein gegangen": "eingegangen",
    "kennen gelernt": "kennengelernt",
    "weiter gefahren": "weitergefahren",
    "an gefragt": "angefragt",
    "an gefallen": "angefallen",
    "zu gestellt": "zugestellt",
    "hin gestreckt": "hingestreckt",
    "weg gegangen": "weggegangen",
    "aus gedruckt": "ausgedruckt",
    "nach geführt": "nachgeführt",
    "hin gehalten": "hingehalten",
    "ab gespeichert": "abgespeichert",
    "aus geführt": "ausgeführt",
    "auf genommen": "aufgenommen",
    "zurück gekehrt": "zurückgekehrt",
    "mit bekommen": "mitbekommen",
    "hervor gekommen": "hervorgekommen",
    "herüber gekommen": "herübergekommen",
    "weg gekommen": "weggekommen",
    "runter gekommen": "runtergekommen",
    "runter gegangen": "runtergegangen",
    "rauf gekommen": "raufgegangen",
    "rauf gegangen": "raufgegangen",
    "heim gekommen": "heimgekommen",
    "heim gegangen": "heimgegangen",
    "vor gekommen": "vorgekommen",
    "hervor gegangen": "hervorgegangen",
    "nach gefragt": "nachgefragt",
    "zurück gekommen": "zurückgekommen",
    "hin gekommen": "hingekommen",
    "rauf gekommen": "raufgekommen",
    "kennen zu lernen": "kennenzulernen",
    "los gegangen": "losgegangen",
    "an geschaut": "angeschaut",
    "ein gerichtet": "eingerichtet",
    "aus gerichtet": "ausgerichtet",
    "vor gelegen": "vorgelegen",
    "ab gelaufen": "abgelaufen",
    "durch geführt": "durchgeführt",
    "fest gestellt": "festgestellt",
    "an gekündigt": "angekündigt",
    "an gewiesen": "angewiesen",
    "hin gewiesen": "hingewiesen",
    "an gemeldet": "angemeldet",
    "auf gefordert": "aufgefordert",
    "an gefordert": "angefordert",
    "ab gesagt": "abgesagt", 
    "zu gesagt": "zugesagt",
    "ein bezahlt": "einbezahlt",
    "nach gedacht": "nachgedacht",
    "ein gestiegen": "eingestiegen",
    "ab gehoben": "abgehoben",
    "aus gesagt": "ausgesagt",
    "teil genommen": "teilgenommen",
    "klar gemacht": "klargemacht",
    "fest gehalten": "festgehalten",
    "auf gehalten": "aufgehalten",
    "durch gehalten": "durchgehalten",
    "durch gegeben": "durchgegeben",
}
